name: Test
on: 
   workflow_dispatch

jobs:
   build:
     runs-on: ubuntu-22.04

     steps:
        - uses: actions/checkout@v4
        - name: Run one-line script
          run: echo " Hello Wasif"
